.travis.yml
config.sh

0.8.0 isn't final yet, but I wanted to test and see if we need any changes for this build to work.

WIP: Update submodules for 0.8.0

---

.travis.yml
appveyor.yml

Build v0.10.0

---

.travis.yml
appveyor.yml

MAINT: Update versions

---

.travis.yml
appveyor.yml

MAINT: Trigger CI for 0.10.1

---

.travis.yml
appveyor.yml

Try to get Windows 3.6 to build by pinning
[skip travis]

MAINT: Fix merge conflict

---

.travis.yml
appveyor.yml

Try to see if 3.8 will build
Restrict xdist

MAINT: Try 3.8 build for Windows

---

.travis.yml
appveyor.yml

Test master for 0.11 rc

---

.travis.yml
appveyor.yml

BLD: Build 0.11 rc1

---

appveyor.yml

BLD: Build 3.8 wheels for 0.10.2

---

appveyor.yml

[skip ci]
Restore Python < 3.8

MAINT: Restore remainder of 0.10 builds

---

.travis.yml

[skip apppveyor]
Build missing i686 on Linux

BLD: Build i686

---

.travis.yml

BLD: Add Python 3.7 and 3.8 32 bit for Linux

---

.travis.yml
appveyor.yml

Update to reflect v0.11 changes

BLD: Update master [skip ci]

---

appveyor.yml

[skip ci]
Restore missing jobs

MAINT: Restore full appveyor config

---

.travis.yml
appveyor.yml

MAINT: Update requirements

---

.travis.yml
appveyor.yml

Try anaconda again

---

.travis.yml
anaconda.org/upload-anaconda.ps1
anaconda.org/upload-anaconda.sh
appveyor.yml

Fix upload on Travis

---

.travis.yml
anaconda.org/upload-anaconda.ps1
anaconda.org/upload-anaconda.sh
appveyor.yml

Switch nightly and staging to shared resorces

Switch to shared anaconda.org resources

---

.travis.yml
appveyor.yml

BLD: Test build of 0.12.1

---

.github/workflows/build-wheels.yml

Move i686, x86_64 and mac builds to Github to preserve Travis credits.

Move x86 and mac builds to GitHub

---

.github/workflows/build-wheels.yml

Fetch tags to get correct tagged builds

MAINT: Fetch tags

---

.github/workflows/build-wheels.yml

Try and get 0.12 to upload correctly

MAINT: Attempt to get 0.12 to upload

---

.github/workflows/build-wheels.yml
config.sh

MAINT: Corect variable name

---

.github/workflows/build-wheels.yml

MAINT: Port over 0.12 changes

---

.github/workflows/build-wheels.yml

aarch64 emulation is unbuildable

REVERT: Remvoe aarch64

---

.github/workflows/build-wheels.yml

Remove aarch64 build using QEMU as it cannot succeed

MAINT: Remove aarch64 build

---

.github/workflows/build-wheels.yml
README.md
anaconda.org/upload-anaconda.ps1
anaconda.org/upload-anaconda.sh

Update to use new location for nightly builds:
https://anaconda.org/scientific-python-nightly-wheels/
More details are available here:
https://scientific-python.org/specs/spec-0004/
Also see https://github.com/statsmodels/statsmodels/pull/8899

Upload nighlighties to new location

---

.github/dependabot.yml
.github/workflows/build-wheels.yml

BLD: Change target to 0.14 branch
